export const gameRatingSeeds = {
  'flappy-bird': [
    {
      id: 'seed-flappy-bird-1',
      name: 'Marcus T.',
      rating: 5,
      comment: 'The Spiderman reskin is such a fun touch, love the web pipes.',
      timestamp: '2026-08-10T14:22:00.000Z',
    },
    {
      id: 'seed-flappy-bird-2',
      name: 'Priya K.',
      rating: 4,
      comment: 'Controls feel tight, just wish the pipes were a bit slower.',
      timestamp: '2026-08-11T09:05:00.000Z',
    },
    {
      id: 'seed-flappy-bird-3',
      name: 'Daniel R.',
      rating: 5,
      comment: 'Got 14 on my third try, addictive little game!',
      timestamp: '2026-08-12T18:40:00.000Z',
    },
    {
      id: 'seed-flappy-bird-4',
      name: 'Sofia M.',
      rating: 3,
      comment: 'Fun but a little too hard on mobile for me.',
      timestamp: '2026-08-13T11:15:00.000Z',
    },
    {
      id: 'seed-flappy-bird-5',
      name: 'Jamal W.',
      rating: 5,
      comment: 'Best flappy bird clone I have played in a while.',
      timestamp: '2026-08-14T20:02:00.000Z',
    },
    {
      id: 'seed-flappy-bird-6',
      name: 'Elena V.',
      rating: 4,
      comment: 'Cool art style, the canvas filling the window is a nice touch.',
      timestamp: '2026-08-15T13:47:00.000Z',
    },
    {
      id: 'seed-flappy-bird-7',
      name: 'Tom H.',
      rating: 5,
      comment: 'Nailed the nostalgia, love the Spiderman theme.',
      timestamp: '2026-08-16T08:30:00.000Z',
    },
    {
      id: 'seed-flappy-bird-8',
      name: 'Grace L.',
      rating: 4,
      comment: 'Great little break from browsing the portfolio.',
      timestamp: '2026-08-17T16:58:00.000Z',
    },
    {
      id: 'seed-flappy-bird-9',
      name: 'Victor A.',
      rating: 5,
      comment: 'Simple, polished, and surprisingly hard to put down.',
      timestamp: '2026-08-18T10:12:00.000Z',
    },
  ],
  'typing-speed': [
    {
      id: 'seed-typing-speed-1',
      name: 'Nadia S.',
      rating: 5,
      comment: 'Level 30 and still climbing, love the escalating difficulty.',
      timestamp: '2026-08-10T15:10:00.000Z',
    },
    {
      id: 'seed-typing-speed-2',
      name: 'Owen P.',
      rating: 4,
      comment: 'Great way to warm up before work, my WPM is improving.',
      timestamp: '2026-08-11T12:25:00.000Z',
    },
    {
      id: 'seed-typing-speed-3',
      name: 'Lin C.',
      rating: 5,
      comment: 'The classroom scene background is a nice detail.',
      timestamp: '2026-08-12T19:33:00.000Z',
    },
    {
      id: 'seed-typing-speed-4',
      name: 'Ahmed F.',
      rating: 3,
      comment: 'Solid game, wish there was a practice mode with no timer.',
      timestamp: '2026-08-13T09:47:00.000Z',
    },
    {
      id: 'seed-typing-speed-5',
      name: 'Isabella G.',
      rating: 5,
      comment: 'Hit level 22 on my first real attempt, super satisfying.',
      timestamp: '2026-08-14T14:58:00.000Z',
    },
    {
      id: 'seed-typing-speed-6',
      name: 'Ryan D.',
      rating: 4,
      comment: 'Good challenge, the speed ramp keeps it interesting.',
      timestamp: '2026-08-15T17:20:00.000Z',
    },
    {
      id: 'seed-typing-speed-7',
      name: 'Mei T.',
      rating: 5,
      comment: 'Best typing test I have tried online, clean UI too.',
      timestamp: '2026-08-16T11:05:00.000Z',
    },
    {
      id: 'seed-typing-speed-8',
      name: 'Carlos N.',
      rating: 4,
      comment: 'Score card at the end is a nice touch when you fail.',
      timestamp: '2026-08-17T08:41:00.000Z',
    },
    {
      id: 'seed-typing-speed-9',
      name: 'Hannah B.',
      rating: 5,
      comment: '100 levels is ambitious, made it to 45 so far.',
      timestamp: '2026-08-18T20:15:00.000Z',
    },
  ],
  'memory-flip': [
    {
      id: 'seed-memory-flip-1',
      name: 'Diego M.',
      rating: 5,
      comment: 'The 3D flip animation is so satisfying, great feel.',
      timestamp: '2026-08-10T16:38:00.000Z',
    },
    {
      id: 'seed-memory-flip-2',
      name: 'Yuki H.',
      rating: 4,
      comment: 'Lives system adds real tension once boards get bigger.',
      timestamp: '2026-08-11T10:52:00.000Z',
    },
    {
      id: 'seed-memory-flip-3',
      name: 'Fatima Z.',
      rating: 5,
      comment: 'Reached level 35, the sound effects are a great touch.',
      timestamp: '2026-08-12T13:29:00.000Z',
    },
    {
      id: 'seed-memory-flip-4',
      name: 'Noah K.',
      rating: 3,
      comment: 'Fun climb, boards get pretty large near the higher levels.',
      timestamp: '2026-08-13T18:11:00.000Z',
    },
    {
      id: 'seed-memory-flip-5',
      name: 'Aaliyah J.',
      rating: 5,
      comment: 'Love the background music, very chill while playing.',
      timestamp: '2026-08-14T09:24:00.000Z',
    },
    {
      id: 'seed-memory-flip-6',
      name: 'Lucas F.',
      rating: 4,
      comment: 'Game over card looks great, clear replay/exit buttons.',
      timestamp: '2026-08-15T15:47:00.000Z',
    },
    {
      id: 'seed-memory-flip-7',
      name: 'Chloe R.',
      rating: 5,
      comment:
        'Surprisingly deep for a memory game, the level climb hooked me.',
      timestamp: '2026-08-16T12:03:00.000Z',
    },
    {
      id: 'seed-memory-flip-8',
      name: 'Ethan S.',
      rating: 4,
      comment: 'Nice variety of icons, keeps each run feeling fresh.',
      timestamp: '2026-08-17T19:56:00.000Z',
    },
    {
      id: 'seed-memory-flip-9',
      name: 'Zara Q.',
      rating: 5,
      comment: 'Best of the three arcade games, could play this for hours.',
      timestamp: '2026-08-18T07:40:00.000Z',
    },
  ],
}
